[config]
default_to_workspace = false

[tasks.test]
command = "cargo"
args = ["hack", "t", "--lib", "--feature-powerset"]

[tasks.doc_test]
command = "cargo"
args = ["t", "--doc", "--all-features"]

[tasks.watch_doc]
env = { RUSTDOCFLAGS="--cfg docsrs" }
command = "cargo"
args = ["watch", "-w", "src", "-x", "+nightly doc --all-features --no-deps"]

[tasks.doc]
env = { RUSTDOCFLAGS = "--cfg docsrs" }
command = "rustup"
args = ["run", "nightly", "cargo", "doc", "--all-features", "--no-deps"]

[tasks.check]
env = { RUSTFLAGS="-D warnings" }
command = "cargo"
args = ["hack", "clippy", "--feature-powerset", "--all-targets"]

[tasks.tree]
command = "cargo"
args = ["hack", "tree", "-e", "normal,features", "-f", "\"{p} {f}\"", "--feature-powerset"]

[tasks.semver]
command = "cargo"
args = ["semver-checks", "check-release"]
