name: Main CI

on:
  push:
    branches:
      - main
      - nightly
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: Add MIRI
        if: matrix.rust == 'nightly'
        run: rustup component add miri

      # - name: Install cargo-semver-checks
      #   if: matrix.rust == 'stable'
      #   uses: taiki-e/install-action@v2
      #   with:
      #     tool: cargo-semver-checks

      - name: Check (Compilation)
        run: RUSTFLAGS="-D warnings" cargo hack check --feature-powerset --all-targets

      - name: Run Tests
        run: cargo hack test --feature-powerset --lib

      - name: Run Miri on Some Tests
        if: matrix.rust == 'nightly'
        run: cargo hack miri test --feature-powerset --lib "::miri_tests::"

      - name: Run Miri on Some Tests (debug-assertions=off)
        if: matrix.rust == 'nightly'
        run: RUSTFLAGS="-C debug-assertions=off" cargo hack miri test --feature-powerset --lib "::miri_tests::"

      - name: Run Doc Tests
        run: RUSTFLAGS="-D warnings" cargo test --doc --all-features

      - name: Check Formatting
        if: matrix.rust == 'stable'
        run: RUSTFLAGS="-D warnings" cargo fmt --all -- --check

      - name: Lint
        if: matrix.rust == 'stable'
        run: RUSTFLAGS="-D warnings" cargo hack clippy --feature-powerset --all-targets

      # - name: Check SemVer Violation
      #   if: matrix.rust == 'stable'
      #   run: cargo semver-checks check-release
